/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventarisbarang;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author samsung
 */
public class indexFrm extends javax.swing.JFrame {

    /**
     * Creates new form indexFrm
     */
    public indexFrm() {
        initComponents();
        
            String SQL = """
                     SELECT     customers.nama_Customer,     pencatatan_barang.tanggal,     barang.nama_barang, kategori.nama_kategori, barang.harga_barang,     detail_pencatatan_barang.jumlah_barang,     pencatatan_barang.jenis_catatan 
                     FROM     
                     \tdetail_pencatatan_barang 
                     LEFT JOIN    
                     \tpencatatan_barang ON detail_pencatatan_barang.Catatan_id = pencatatan_barang.id_catatan 
                     LEFT JOIN    
                     \tcustomers ON customers.id_Customer = pencatatan_barang.customer_id 
                     LEFT JOIN     
                     \tbarang ON barang.id_barang = detail_pencatatan_barang.Barang_id 
                     LEFT JOIN 
                     \tkategori ON kategori.id_kategori = barang.kategori_id""";
            
        ResultSet rsTable = koneksi.executeQuery(SQL);
        createTable(rsTable);
        
        cbKategori.addItem("Kategori");
        String SQLKategori = "SELECT * FROM kategori";
        ResultSet rsKategori = koneksi.executeQuery(SQLKategori);
        String nama_kategori = "";
        
        try {
            while (rsKategori.next()){
                nama_kategori = rsKategori.getString("nama_kategori");
                cbKategori.addItem(nama_kategori);
            }
        }catch (SQLException ex){
            Logger.getLogger(indexFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    public void doubleFilter(String SQL){        
        String doubleFilter = SQL + " WHERE kategori.nama_kategori='"+cbKategori.getSelectedItem()+"' AND pencatatan_barang.jenis_catatan='"+cbJenisCatatan.getSelectedItem()+"'";
        ResultSet rsDoubleFilter = koneksi.executeQuery(doubleFilter);

        createTable(rsDoubleFilter);
    }
    
    public void createTableListBarang(ResultSet rs){
        String kolom[] = {"No", "Nama", "Harga", "Stok Barang", "Kategori"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        try {
            int no = 1;
            while(rs.next()){
                String nama = rs.getString("nama_barang");
                int harga = rs.getInt("harga_barang");
                int stok = rs.getInt("stok_barang");
                String kategori = rs.getString("nama_kategori");
                
                Object data[] = {no, nama, harga, stok, kategori};
                dtm.addRow(data);
                no++;
            }
            tbData.setModel(dtm);
        }catch (SQLException ex){
            Logger.getLogger(indexFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void createTable (ResultSet rs){
        String kolom[] = {"NO", "Nama", "Tanggal", "Barang", "Harga", "Jumlah Barang", "Jenis Catatan"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        try {
            int no = 1;
            while (rs.next()){
                String nama = rs.getString("nama_Customer");
                String tanggal = rs.getString("tanggal");
                String barang = rs.getString("nama_barang");
                String harga = rs.getString("harga_barang");
                int jumlah = rs.getInt("jumlah_barang");
                String jenis_catatan = rs.getString("jenis_catatan");
                
                Object data[] = {no, nama, tanggal, barang, harga, jumlah, jenis_catatan};
                dtm.addRow(data);
                no++;
            }
            tbData.setModel(dtm);
        }catch (SQLException ex){
            Logger.getLogger(indexFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        cbKategori = new javax.swing.JComboBox<>();
        cbJenisCatatan = new javax.swing.JComboBox<>();
        btnListBarang = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbData = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(720, 540));

        jPanel2.setBackground(new java.awt.Color(243, 251, 237));
        jPanel2.setPreferredSize(new java.awt.Dimension(720, 540));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setText("INV");

        jButton1.setBackground(new java.awt.Color(243, 251, 237));
        jButton1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(124, 156, 108));
        jButton1.setText("BARANG BARU");
        jButton1.setToolTipText("");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(124, 156, 108));
        jPanel3.setPreferredSize(new java.awt.Dimension(640, 60));

        jButton3.setBackground(new java.awt.Color(243, 251, 237));
        jButton3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(124, 156, 108));
        jButton3.setText("TAMBAH STOCK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        cbKategori.setBackground(new java.awt.Color(243, 251, 237));
        cbKategori.setForeground(new java.awt.Color(124, 156, 108));
        cbKategori.setPreferredSize(new java.awt.Dimension(72, 24));
        cbKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKategoriActionPerformed(evt);
            }
        });

        cbJenisCatatan.setBackground(new java.awt.Color(243, 251, 237));
        cbJenisCatatan.setForeground(new java.awt.Color(124, 156, 108));
        cbJenisCatatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua", "Masuk", "Keluar" }));
        cbJenisCatatan.setPreferredSize(new java.awt.Dimension(72, 24));
        cbJenisCatatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJenisCatatanActionPerformed(evt);
            }
        });

        btnListBarang.setBackground(new java.awt.Color(243, 251, 237));
        btnListBarang.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnListBarang.setForeground(new java.awt.Color(124, 156, 108));
        btnListBarang.setText("LIST BARANG");
        btnListBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListBarangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnListBarang)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(cbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbJenisCatatan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbJenisCatatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        jButton2.setBackground(new java.awt.Color(124, 156, 108));
        jButton2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(243, 251, 237));
        jButton2.setText("BARANG KELUAR");
        jButton2.setToolTipText("");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tbData.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        tbData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbData);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 294, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new BarangMasuk().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        new BarangKeluar().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        new TambahStokBarang().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cbJenisCatatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJenisCatatanActionPerformed
        String SQL = """
                     SELECT     customers.nama_Customer,     pencatatan_barang.tanggal,     barang.nama_barang, kategori.nama_kategori, barang.harga_barang,     detail_pencatatan_barang.jumlah_barang,     pencatatan_barang.jenis_catatan 
                     FROM     
                     \tdetail_pencatatan_barang 
                     LEFT JOIN    
                     \tpencatatan_barang ON detail_pencatatan_barang.Catatan_id = pencatatan_barang.id_catatan 
                     LEFT JOIN    
                     \tcustomers ON customers.id_Customer = pencatatan_barang.customer_id 
                     LEFT JOIN     
                     \tbarang ON barang.id_barang = detail_pencatatan_barang.Barang_id 
                     LEFT JOIN 
                     \tkategori ON kategori.id_kategori = barang.kategori_id""";        
        if (cbJenisCatatan.getSelectedItem().equals("masuk")){
            String SQLFilter = SQL + " WHERE pencatatan_barang.jenis_catatan = 'Masuk'";
            ResultSet rs = koneksi.executeQuery(SQLFilter);
            createTable(rs);
        }else if (cbJenisCatatan.getSelectedItem().equals("Keluar")){
            String SQLFilter = SQL + " WHERE pencatatan_barang.jenis_catatan = 'Keluar'";            
            ResultSet rs = koneksi.executeQuery(SQLFilter);
            createTable(rs);
        }else {            
            ResultSet rs = koneksi.executeQuery(SQL);
            createTable(rs);
        }
        
        if(!"Semua".equals(cbJenisCatatan.getSelectedItem()) && !"Kategori".equals(cbKategori.getSelectedItem())){
            doubleFilter(SQL);
        }
        
//        String kolom[] = {"NO", "Nama", "Tanggal", "Barang", "Harga", "Jumlah Barang", "Jenis Catatan"};
//        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
//        try {
//            int no = 1;
//            while (rs.next()){
//                String nama = rs.getString("nama_Customer");
//                String tanggal = rs.getString("tanggal");
//                String barang = rs.getString("nama_barang");
//                String harga = rs.getString("harga_barang");
//                int jumlah = rs.getInt("jumlah_barang");
//                String jenis_catatan = rs.getString("jenis_catatan");
//                
//                Object data[] = {no, nama, tanggal, barang, harga, jumlah, jenis_catatan};
//                dtm.addRow(data);
//                no++;
//            }
//            tbData.setModel(dtm);
//        }catch (SQLException ex){
//            Logger.getLogger(indexFrm.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_cbJenisCatatanActionPerformed

    private void cbKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKategoriActionPerformed
                String SQL = """
                     SELECT     customers.nama_Customer,     pencatatan_barang.tanggal,     barang.nama_barang, kategori.nama_kategori, barang.harga_barang,     detail_pencatatan_barang.jumlah_barang,     pencatatan_barang.jenis_catatan 
                     FROM     
                     \tdetail_pencatatan_barang 
                     LEFT JOIN    
                     \tpencatatan_barang ON detail_pencatatan_barang.Catatan_id = pencatatan_barang.id_catatan 
                     LEFT JOIN    
                     \tcustomers ON customers.id_Customer = pencatatan_barang.customer_id 
                     LEFT JOIN     
                     \tbarang ON barang.id_barang = detail_pencatatan_barang.Barang_id 
                     LEFT JOIN 
                     \tkategori ON kategori.id_kategori = barang.kategori_id""";
                
        if (!cbKategori.getSelectedItem().equals("Kategori")){
            String SQLFilter = SQL + " WHERE kategori.nama_kategori = '"+cbKategori.getSelectedItem()+"'";
            ResultSet rs = koneksi.executeQuery(SQLFilter);
            createTable(rs);
        }
    }//GEN-LAST:event_cbKategoriActionPerformed

    private void btnListBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListBarangActionPerformed
        String SQL = "SELECT barang.*, kategori.nama_kategori FROM barang LEFT JOIN kategori ON barang.kategori_id = kategori.id_kategori;";
        ResultSet rsListTableBarang = koneksi.executeQuery(SQL);
        createTableListBarang(rsListTableBarang);
    }//GEN-LAST:event_btnListBarangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(indexFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(indexFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(indexFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(indexFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new indexFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListBarang;
    private javax.swing.JComboBox<String> cbJenisCatatan;
    private javax.swing.JComboBox<String> cbKategori;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbData;
    // End of variables declaration//GEN-END:variables
}
